# Required
version: 2

# Build environment settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt