##################################### Process Description ############################################################################
# Process Name
name: Atomic Layer Etching

# A short Process Description
description: Atomic Layer Etching (ALE) is a highly controlled, layer-by-layer etching process used in semiconductor fabrication to achieve atomic-scale precision in material removal.

##################################### Stage 1 Prompt Specification ###################################################################

# Stage 1 Objectives
stage1_objectives: | 
  Using the context from the specification document, extract and define a JSON schema that accurately represents the Atomic Layer Etching process. The schema should:

  1. Include all essential properties related to the Atomic Layer Etching process.
  2. Structure the JSON schema in a way that captures relationships between properties, nested as needed (e.g., grouping properties that are part of the same process stage).
  3. Use appropriate data types (e.g., string, number, array, boolean, object) for each property.
  4. Document each property's role, constraints, and any default values or units if applicable (e.g., temperature in Celsius, pressure in Pascals).

# Stage 1 User Prompt Conditions
stage1_user_prompt_conditions: |
  1. Include all relevant properties.
  2. Use standard JSON schema format with appropriate data types, descriptions, and units where applicable.
  3. Group related parameters in nested objects as needed to reflect the Atomic Layer Etching process structure.

######################################################################################################################################
##################################### Stage 2 Prompt Specification ###################################################################

#Stage 2 Objectives
stage2_objectives: |
  With each research paper and expert feedback, your task is to enhance the schema by:

  1. Validating Existing properties: Ensure that each property in the schema aligns with findings from the current research paper and expert feedback. Modify property definitions, constraints, or data types as needed to improve accuracy and clarity.
  2. Adding New properties: If a relevant property is mentioned in the research paper but is missing from the schema, incorporate it, ensuring it has the appropriate data type, description, units, and constraints.
  3. Applying Expert Recommendations: Use expert feedback to guide refinements, adjusting descriptions, data types, or constraints as recommended to ensure the schema aligns with established Atomic Layer Etching standards and practices.
  4. Documenting and Organizing: Keep the JSON schema well-structured, using nested objects where appropriate, and ensure that each new or modified property is documented with descriptions, data types, and any relevant units or constraints.
  5. Avoiding Redundancy and Overspecialization: The schema should remain stable across iterations and must not include unnecessary new properties if they overlap with existing ones or compromise the schema's generality.

#Stage 2 User Prompt Conditions
stage2_user_prompt_conditions: |
  1. Include all relevant properties.
  2. Use standard JSON schema format with appropriate data types, descriptions, and units where applicable.
  3. Group related parameters in nested objects as needed to reflect the Atomic Layer Etching process structure.

######################################################################################################################################
##################################### Stage 3 Prompt Specification ###################################################################

#Stage 3 Objectives
stage3_objectives: |
  With each research paper and expert feedback, your task is to enhance the schema by:

  1. Validating Existing properties: Ensure that each property in the schema aligns with findings from the current research paper and expert feedback. Modify property definitions, constraints, or data types as needed to improve accuracy and clarity.
  2. Adding New properties: If a relevant property is mentioned in the research paper but is missing from the schema, incorporate it, ensuring it has the appropriate data type, description, units, and constraints.
  3. Applying Expert Recommendations: Use expert feedback to guide refinements, adjusting descriptions, data types, or constraints as recommended to ensure the schema aligns with established Atomic Layer Etching standards and practices.
  4. Documenting and Organizing: Keep the JSON schema well-structured, using nested objects where appropriate, and ensure that each new or modified property is documented with descriptions, data types, and any relevant units or constraints.
  5. Avoiding Redundancy and Overspecialization: The schema should remain stable across iterations and must not include unnecessary new properties if they overlap with existing ones or compromise the schema's generality.

#Stage 3 User Prompt Conditions
stage3_user_prompt_conditions: |
  1. Include all relevant properties.
  2. Use standard JSON schema format with appropriate data types, descriptions, and units where applicable.
  3. Group related parameters in nested objects as needed to reflect the Atomic Layer Etching process structure.

######################################################################################################################################